### ISSUE TITLE
Remote support use case

### ISSUE THREAD

**Issue by lephuongbg** [TimeToogo/tunshell#12]
tunshell could be a promising way to do remote support, in case we only need to do some commands on remote computer, no need for full remote desktop solution like VNC or Teamviewer.

There is one missing piece only is:  the remote user should be able to see what the remote support person is doing, i.e tunshell echos what is currently typing and the result of the command on the remote server.

@TimeToogo what is your thought about this?

**Comment by rndmh3ro** [comment]
You could just open a tmux session on the remote server and let the other person also connect to it.

**Comment by TimeToogo** [comment]
Hi @lephuongbg,

I agree the client should support echoing the shell session to the remote terminal. I've just implemented this, so it should be possible to start using this feature today. I haven't gotten around implementing proper argument parsing yet so the usage is a bit cumbersome.

You can try out the functionality by adding the `--echo` arg to the client like so:

```
curl -sSf https://lets.tunshell.com/init.sh | sh /dev/stdin T YeiRiOLhST32g5R0JZeTcc VqRPfLn2uWBcJxANNjJre9 relay.tunshell.com 5000 443 --echo
```
(note you must specify the `5000 443` positional args first until arg parsing is refactored)
