### ISSUE TITLE
In-Browser Session Support

### ISSUE THREAD

**Issue by NyaMisty** [TimeToogo/tunshell#33]
Hi, I'm user of action-tmate, which is another relay tool being widely used in Github Actions.
I'm wondering if tunshell have any plan to implement a terminal in browser just like tmate.io.

And I'm actually curious about the wasm build: can it be used in browser to implement this idea?

**Comment by TimeToogo** [comment]
Hi @NyaMisty,

Thanks for your interest in the project. In-browser terminal support powered by the WASM build is already active on https://tunshell.com 
Let me know if you have any questions about this. 

Thanks
