### ISSUE TITLE
does Tunshell support peer to peer via local LAN without internet connectivity?

### ISSUE THREAD

**Issue by saumilsdk** [TimeToogo/tunshell#48]
does Tunshell support peer to peer via local LAN without internet connectivity?

**Comment by TimeToogo** [comment]
It definitely is possible if you set up a relay server running on your LAN.
You will also have to distribute the tunshell client binaries within your LAN.
The default scripts/UI wont work as they are hard coded to use the existing relay servers / binary endpoints over the internet.
I dont have time to put together a full guide on how to do this so your best bet is to review the existing install scripts and documentation to see how you could apply it to your set up.
