### ISSUE TITLE
Allow more than one connection (like ssh does)

### ISSUE THREAD

**Issue by probonopd** [TimeToogo/tunshell#9]
Getting `[ERROR client] Error occurred: Connection has already been joined by another host` when trying to open more than one tunshell into a machine. Being able to do so would be extremely useful for debugging. For example, one could launch a problematic process in shell number 1 and debug it from shell number 2.

**Comment by TimeToogo** [comment]
This is unlikely to happen but you can look into using [background jobs](https://www.digitalocean.com/community/tutorials/how-to-use-bash-s-job-control-to-manage-foreground-and-background-processes) in bash for handling this scenario.
